### ISSUE TITLE
vpn failover for vpn server

### ISSUE THREAD

**Issue by merwone** [MartineauUK/VPN-Failover#2]
hi Martineau,

this is a request.

is it possible to write a script to check working of vpn server and if failed to restart vpn server?

often when abroad for longer times suddenly i fail to connect to my vpn server.

thanks

**Comment by MartineauUK** [comment]
The firmware currently monitors the existence of both VPN Servers, by  a couple of cron jobs

`cru l | grep CheckVPNServer

*/2 * * * * /etc/openvpn/server1/vpns-watchdog1.sh #CheckVPNServer1#
*/2 * * * * /etc/openvpn/server2/vpns-watchdog2.sh #CheckVPNServer2#
`
although it doesn't obviously allow monitoring the throughput.

I don't think the same logic can be applied to test the inbound connection.
